version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Run Tests
          command: npm test
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build:
    jobs:
      - test